### LU Factorization

Suppose that we had an $n\times n$ matrix $A=LU$ where $L$ is lower triangular and $U$ is upper triagular.  We could use this factorization to solve $Ax=b$ as follows:

1. Rewrite $Ax=b$ as
   
   $$
   LU x = b
   $$ (lueqns)
   
2. Define $y$ by the equation

   $$
    U x=y
   $$

    Note that $LU x=Ly$ so Eq. {eq}`lueqns` becomes

   $$
   Ly=b
    $$
3. Solve $Ly=b$ for $y$ using **forward** substitution.
4. Solve $Ux=y$ for $x$ using *backward* substitution using the $y$ from the previous step.

We saw that backwards substitution was a simple way to solve an upper triangular system of equations that we obtained after Gaussian elimination.  *Forward* substitution is the analagous way of solving a lower triangular system of equations.

How much does this cost?  We saw in the previous section that backward substitution cost $\sim \frac{n^2}{2}$ flops.  As forward substitution is just the same sequance of operations just from top to bottom rather than bottom to top, it should also cost $\sim \frac{n^2}{2}$ flops.  Which gives us a total of $n^2$ flops which is *much* faster than the $\frac{n^3}{3}$ required for the full Gaussian elimination and back substitution.

The following example illustrates that steps

**Example**  Given the following factorization of a matrix, 

$$
\begin{align}
  \underbrace{\left[ {\begin{array}{ccc}
    2 &  6 & 2 \\
    -3 &  -8 & 0 \\
     4 &  9 & 2 \\
  \end{array} } \right]}_{A} =
  \underbrace{\left[ {{\begin{array}{ccc}
  2 & 0 & 0 \\
  -3 & 1 & 0 \\
  4 & -3 & 7 \\
  \end{array}}} \right]}_{L} 
  \underbrace{\left[ {{\begin{array}{ccc}
  1 & 3 & 1 \\
  0 & 1 & 3 \\
  0 & 0 & 1 \\
  \end{array}}} \right]}_{U} 
\end{align}
$$

which you can easily verify by multiplying out the $L$ and $U$, we want to solve $Ax=b$ with

$$
b=\left[\begin{array}{c}
2 \\
2 \\
3 \\
\end{array}\right].
$$

We first need to solve $Ly=b$ for $y$, i.e.

$$
\begin{align}
\left[ {{\begin{array}{ccc}
  2 & 0 & 0 \\
  -3 & 1 & 0 \\
  4 & -3 & 7 \\
  \end{array}}} \right]
  \left[\begin{array}{c}
y_1 \\
y_2 \\
y_3 \\
\end{array}\right]=
\left[\begin{array}{c}
2 \\
2 \\
3 \\
\end{array}\right]
\end{align}
$$

using forward substitution:

$$
\begin{align}
2 y_1 &= 2\quad \Rightarrow y_1=1\\
y_2 &= \frac{2+3y_1}{1}=5\\
y_3 &= \frac{3-(4y_1-3y_2)}{7}=2\\
\end{align}
$$

then we solve $U x=y$ for $x$, i.e.

$$
\begin{align} 
\left[{{\begin{array}{ccc}
  1 & 3 & 1 \\
  0 & 1 & 3 \\
  0 & 0 & 1 \\
  \end{array}}} \right]
  \left[\begin{array}{c}
x_1 \\
x_2 \\
x_3 \\
\end{array}\right]=
\left[\begin{array}{c}
1\\
5 \\
2 \\
\end{array}\right]
\end{align}
$$

using backward substitution:

$$
\begin{align}
x_3&=2\\
x_2&=5-3 x_3 = -1\\
x_1&=1-x_3-3x_2 = 2
\end{align}
$$

So the solution is 

$$
x=\left[\begin{array}{c}
2 \\
-1 \\
2 \\
\end{array}\right].
$$

$\blacksquare$

This brings up the question of: How do we $LU$ factorize a matrix $A$ and when can we do this?  This is answered in the following theorem.

> **Theorem:**
> If Gaussian elimination can be performed on $Ax=b$ *without* row interchanges, then $A$ can be factored into $A=LU$, where $U$ is the resulting matrix after forward elimination and $L$ is the lower triangular matrix of multipliers and diagonal elements 1.

The theorem should not be a massive surprise as it is literally just a translation of the reverse of the linear operations performed in the inner loop of Gaussian (forward) elimination into matrix algebra.  We illustrate the process in the following example.

**Example**  We want to $LU$-factorize the following matrix:

$$
\begin{align}
  A=\left[ {\begin{array}{cccc}
     1 &  1 & 0 &  3 \\
     2 &  1 & -1 &  1 \\
     3 &  -1 & -1 &  2 \\
     -1 &  2 & 3 &  -1 \\
  \end{array} } \right].
\end{align}
$$

To do so, we first just perform Gaussian elimination to row reduce to get $U$

$$
\begin{align}
 {\begin{array}{cc}
 E_1 &:\\
 (E_2-\textcolor{red}{2}E_1)\rightarrow E_2 &: \\
 (E_3-\textcolor{red}{3}E_1)\rightarrow E_3 &: \\
 (E_4-\textcolor{red}{(-1)}E_1)\rightarrow E_4 &: \\
 \end{array}}\qquad
  \left[ {\begin{array}{cccc}
     1 &  1 & 0 &  3 \\
     0 &  -1 & -1 &  -5 \\
     0 &  -4 & -1 &  -7 \\
     0 &  3 & 3 &  2 \\
  \end{array} } \right]
\end{align}
$$

We note the multipliers used (in red above) which we will use to construct $L$ below. Moving on to the next step in row reduction:

$$
\begin{align}
 {\begin{array}{cc}
 E_1 & :\\
 E_2 & :\\
 (E_3-\textcolor{blue}{4}E_2)\rightarrow E_3 &:\\
 (E_4-\textcolor{blue}{(-3)}E_2)\rightarrow E_4 &:\\
 \end{array}}\qquad \underbrace{
  \left[ {\begin{array}{cccc}
     1 &  1 & 0 &  3 \\
     0 &  -1 & -1 &  -5 \\
     0 &  0 & -3 &  13 \\
     0 &  0 & 0 &  -13 \\
  \end{array} } \right]}_{U}
\end{align}
$$

Normally we would need one final row reduction to reduce the coefficient matrix to an *upper triangular matrix* $U$, but in this case we see that it is already there, and the multiplier needed to reduce the the last row is just $\textcolor{green}{0}$.  To construct $L$, we just fill in the multipliers used to zero each component into a matrix with diagonal's $1$:

$$
\begin{align}
 L=
  \left[ {\begin{array}{cccc}
     1 &  0 & 0 &  0 \\
     \textcolor{red}{2} &  1 & 0 &  0 \\
     \textcolor{red}{3} &  \textcolor{blue}{4} & 1 &  0 \\
     \textcolor{red}{-1} &  \textcolor{blue}{-3} & \textcolor{green}{0} &  1 \\
  \end{array} } \right]
\end{align}
$$

You can easily verify by direct multiplication of $L$ by $U$ that this does indeed give us back our original matrix $A$.

$\blacksquare$

It should be clear from the above that $LU$ factorization and Gaussian elimination are equivalent amounts of work ($\sim n^3/3$ flops) as they consist of the same operations.  So where do we get any cost savings from using $LU$ factorization to solve linear systems?  The key factor is that now we can solve any number of systems that have the same coefficient matrix, but different right-hand sides (the $b$ in $Ax=b$), while doing the costly $n^3/3$ bit *only once*.  For a $100\times 100$ system this means that we can solve with roughly $35$ different $b$'s in the same time that it would take to do the full Gaussian elimination and back substitution twice.  For larger systems or a larger number of different $b$'s the savings are even greater.

What about row interchanges?  We can describe row interchanges in terms of a *permutation matrix*.

> **Definition:** A $n\times n$ *permutation matrix* $P=[p_{ij}]$ is obtained by rearranging the rows of the identity matrix $I_n$.

We can use the permutation matrix as an operator to rearrange the rows of another $n\times n$ matrix $A$ in the same way that the permutation matrix had its rows rearranged from the identity.

**Example**

$$
\begin{align}
  P=\left[ {\begin{array}{ccc}
     1 &  0 & 0  \\
     0 &  0 & 1 \\
     0 &  1 & 0 \\
  \end{array} } \right].
\end{align}
$$

is obtained from the identity matrix by swapping the second and third rows.  If we multiply a generic $3\times 3$ matrix $A$ by $P$, it will swap the corresponding rows in $A$:

$$
\begin{align}
  PA=\left[ {\begin{array}{ccc}
     1 &  0 & 0  \\
     0 &  0 & 1 \\
     0 &  1 & 0 \\
  \end{array} } \right]
  \left[ {\begin{array}{ccc}
     a_{11} &  a_{12} & a_{13}  \\
     a_{21} &  a_{22} & a_{23} \\
     a_{31} &  a_{32} & a_{33} \\
  \end{array} } \right]=
  \left[ {\begin{array}{ccc}
     a_{11} &  a_{12} & a_{13}  \\
     a_{31} &  a_{32} & a_{33} \\
     a_{21} &  a_{22} & a_{23} \\
  \end{array} }\right]
\end{align}
$$

$\blacksquare$

Another useful property of permutation matrices is that the inverse $P^{-1}$ exists and $P^{-1}=P^t$, the transpose.

If we know all row interchanges that will be used in Gaussian elimination with pivoting, then we could $LU$ factorize $PA$ where $P$ is the permuation matrix corresponding to the row interchanges done in the pivot steps:

$$
\begin{align}
PA&=LU\\
\Rightarrow A &= P^{-1}LU = P^tLU
\end{align}
$$

and for $Ax=b$ we solve $PA x = Pb$ i.e. we need to reorder $b$ too, just as we would have if it had been part of the augmented matrix for Gaussian elimination.  In practice, it is inefficient to store $P$ as it is mostly zeros.  It is better to store the row indices needed to construct $P$, i.e. our previous row index array from partial pivoting.

In [1]:
import numpy as np

def PLUFactorization(A,n):
    # setup our row index array
    nrows=np.array(range(0,n),dtype=int)
    for k in range(0,n-1):
        # select pivot element A[k,k]
        pivot = A[nrows[k],k]
        prow = nrows[k]
        for p in range(k+1,n):
            if (abs(A[nrows[p],k]) > abs(pivot)) :
                prow = p
                pivot = A[nrows[p],k]
        if (prow != nrows[k]) :
            if (pivot == 0) :
                print("Singular Matrix Encountered\n")
                return nrows
            # As rows may have been swapped previously, we need to double index nrows
            tmp = nrows[nrows[k]]
            nrows[nrows[k]]=nrows[nrows[prow]]
            nrows[nrows[prow]]=tmp
        # Now we loop over i, the rows below the pivot row
        for i in range(k+1,n):
            m=A[nrows[i],k]/pivot
            # The multiplier would normally zero out A[nrows[i],k]. Rather than storing
            # the zero we will store the multiplier, as that is what is needed for L:
            A[nrows[i],k] = m
            # Loop over j, the columns of row i
            # The line below is equivalent to the following loop,
            # for j in range(k,n+1):
            #    A[i,j] -= m*A[k,j]
            A[nrows[i], (k+1):] -= m*A[nrows[k], (k+1):]
    return nrows

def ForwardSubstitution(L,b,n,nrows):
    y=np.zeros(n)
    # We don't need to do any division here as diagonals of L are one
    y[0]=b[nrows[0]]
    for k in range(1,n):
        y[k]=b[nrows[k]]
        for j in range(0,k):
            y[k] -= L[nrows[k],j]*y[j]
        # Note: L has diagonal elements one that are not stored.  If that
        # was not the case we would need to divide by L[n[rows[k],k] here
    return y

def BackSubstitution(U,y,n,nrows):
    x=np.zeros(n)
    x[n-1]=y[n-1]/U[nrows[n-1],n-1]
    for k in range(n-2,-1, -1):
        x[k]=y[k]
        for j in range(k+1,n):
            x[k] -= U[nrows[k],j]*x[j]
        x[k]=x[k]/U[nrows[k],k]
    return x

# Problem from our original example from Gaussian elimination with 2nd and last row swapped so no row interchanges
CoefficientMatrix=np.array([[1,1,1,1],[1,4,16,64],[1,3,9,27],[1,2,4,8]],dtype=np.float64)
print("Cofficient Matrix:\n", CoefficientMatrix)
rowsindx=PLUFactorization(CoefficientMatrix,4)
print("LU Factors stored in single matrix:\n", CoefficientMatrix)
print("row index:\n",rowsindx)

# Need to swap elements of b too
b = np.array([3,0,-5,-2],dtype=np.float64)
print("right hand side",b)
my_y = ForwardSubstitution(CoefficientMatrix,b,4,rowsindx)
print("y from solving Ly=b",my_y)
my_x = BackSubstitution(CoefficientMatrix,my_y,4,rowsindx)
print("solution:\n",my_x,"\n")

# The problem from our original example that swapped rows during partial pivoting:
CoefficientMatrix=np.array([[1,1,1,1],[1,2,4,8],[1,3,9,27],[1,4,16,64]],dtype=np.float64)
#CoefficientMatrix=np.array([[1,1,1,1],[1,4,16,64],[1,3,9,27],[1,2,4,8]],dtype=np.float64)
print("Cofficient Matrix:\n", CoefficientMatrix)
rowsindx=PLUFactorization(CoefficientMatrix,4)
print("LU Factors stored in single matrix:\n", CoefficientMatrix)
print("row index:\n",rowsindx)

b = np.array([3,-2,-5,0],dtype=np.float64)
print("right hand side",b)
my_y = ForwardSubstitution(CoefficientMatrix,b,4,rowsindx)
print("y from solving Ly=b",my_y)
my_x = BackSubstitution(CoefficientMatrix,my_y,4,rowsindx)
print("solution:\n",my_x)

Cofficient Matrix:
 [[ 1.  1.  1.  1.]
 [ 1.  4. 16. 64.]
 [ 1.  3.  9. 27.]
 [ 1.  2.  4.  8.]]
LU Factors stored in single matrix:
 [[  1.           1.           1.           1.        ]
 [  1.           3.          15.          63.        ]
 [  1.           0.66666667  -2.         -16.        ]
 [  1.           0.33333333   1.           2.        ]]
row index:
 [0 1 2 3]
right hand side [ 3.  0. -5. -2.]
y from solving Ly=b [ 3. -3. -6.  2.]
solution:
 [ 4.  3. -5.  1.] 

Cofficient Matrix:
 [[ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]
 [ 1.  4. 16. 64.]]
LU Factors stored in single matrix:
 [[  1.           1.           1.           1.        ]
 [  1.           0.33333333   1.           2.        ]
 [  1.           0.66666667  -2.         -16.        ]
 [  1.           3.          15.          63.        ]]
row index:
 [0 3 2 1]
right hand side [ 3. -2. -5.  0.]
y from solving Ly=b [ 3. -3. -6.  2.]
solution:
 [ 4.  3. -5.  1.]


We see that the $PLU$ factorization routine is almost identical to our previous ForwardElimination routine with partial pivoting. The only difference is that we save the multipliers $m$ in the lower triangular part of the matrix to form $L$ and we pass in just the coefficient matrix (it doesn't have the extra column of the augmented matrix).  The back substitution routine is also very similar except we also need to pass in the right hand side (the $y$ in this case) as it is not stored in the $U$ matrix, unlike the row reduced augmented matrix.

Finding the inverse is one case where we need to repeated solve.  The matrix equation, $AA^{-1} = I$ is equivalent to solving the $n$ linear systems

$$
Ax_1=e_1,\quad Ax_2=e_2,\quad \cdots,\quad Ax_n=e_n
$$

where 

$$
e_j=\left[{\begin{array}{c}
     0 \\
     \vdots \\
     0 \\
     1 \\
     0 \\
     \vdots\\
     0 \\
  \end{array} } \right]
$$

where the $1$ is in the $j$'th row and $x_1,\cdots,x_n$ are the columns of $A^{-1}$.

The following example illustrates the process:

In [2]:
# Again from our original example:
My_Matrix=np.array([[1,1,1,1],[1,2,4,8],[1,3,9,27],[1,4,16,64]],dtype=np.float64)
print("My Matrix:\n", My_Matrix)
rowsindx=PLUFactorization(My_Matrix,4)

My_Inverse=np.zeros((4,4))
for j in range(0,4):
    e_j=np.zeros(4)
    e_j[j]=1
    my_y = ForwardSubstitution(My_Matrix,e_j,4,rowsindx)
    my_x = BackSubstitution(My_Matrix,my_y,4,rowsindx)
    My_Inverse[:,j]=my_x

print("Inverse of My Matrix:\n",My_Inverse)

My Matrix:
 [[ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]
 [ 1.  4. 16. 64.]]
Inverse of My Matrix:
 [[ 4.         -6.          4.         -1.        ]
 [-4.33333333  9.5        -7.          1.83333333]
 [ 1.5        -4.          3.5        -1.        ]
 [-0.16666667  0.5        -0.5         0.16666667]]


You can easily check by direct multiplication that the result is correct.  It should be clear from this example though why we do NOT solve $Ax=b$ by finding $A^{-1}$ and then forming $x=A^{-1}b$.  Finding $A^{-1}$ requires factorization ($\sim n^3/3$ flops) and then solving $n$ linear systems using the factorization (each on cost $n^2$ flops and there are $n$ of them, so $n^3$ flops).  That is significantly more work than just solving $Ax=b$ directly and even if we want to solve for multiple $b$'s the matrix multiplication to form $x=A^{-1}b$ cost just as much as solving for $x$ using the $LU$ factorization of $A$.  

Note that our algorithm choice of having $1$'s on the diagonal of $L$ is not unique.  That particular choice is referred to as *Dolittle* factorization.  The observant reader would have noticed that the initial example of an $LU$ factorized matrix that we gave at the top of this page actually had $1$'s on the diagonal of $U$ while the diagonal of $L$ had nonunit entries, a choice known as *Crout*'s factorization.  Another choice, *Cholesky*'s factorization, has diagonal entries of $U$, $u_{kk}$, and diagonal elements of $L$, $l_{kk}$ that are equal, i.e. $l_{kk}=u_{kk}$. 